### ISSUE TITLE
JavaCoder 2.0 in

### ISSUE THREAD

**Issue by dumblob** [andriydruk/swift-java-coder#9]
The sample application https://github.com/readdle/swift-android-architecture has several comments `remove after JavaCoder 2.0` or similar. But looking at the tags in this repository there is no such version.

Could you clarify what's the current state and whether JavaCoder will be further developed?

**Comment by andriydruk** [comment]
Hi, 

Yes, we have few ideas on how to improve our Swift <-> Java interoperability. And one of these improvements include drop java_swift and significant update of Java and JavaCoder (probably that will be version 2.0)

Currently, JavaCoder is supported and improve from time to time. The last big improvement is Kotlin support in branch `dev/kotlin-support`

**Comment by dumblob** [comment]
Ok, thanks. I'll follow your efforts and if there'll be some roadmap or even todo list, I'll consider joining your efforts in one way or another.

Feel free to keep me updated.
